# Generated by Django 3.1.5 on 2021-01-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0002_auto_20201217_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.TextField(default='http://www.buildingfuturesinc.com/Building_Futures,_Inc./Trip_Photos/Pages/Masai_Mara_files/Media/AEJ_3825/AEJ_3825.jpg?disposition=download'),
        ),
    ]
